# Define your configuration properties here
defaultName=Hello, World!<% if (jwtAuth) { %>
# MicroProfile JWT Authentication configuration
# Set the location of your JWT issuer's public key (PEM file or HTTPS JWKS URL)
mp.jwt.verify.publickey.location=/publicKey.pem
# Set the expected issuer claim value to match your token provider
mp.jwt.verify.issuer=https://example.com<% } %>